name: Build

on:
  push:
    branches: [ "**" ]

jobs:
  build-bookmarker-api:
    name: Build bookmark-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: 'maven'


      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bookmark-api:11.27
