  version: '3.8'
  services:
    bookmark-db:
      image: postgres:14-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=appdb
      ports:
        - "15432:5432"

    bookmark-api:
      build:
        dockerfile: Dockerfile
      environment:
        SPRING_PROFILES_ACTIVE: docker
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
        SPRING_DATASOURCE_URL: jdbc:postgresql://bookmark-db:5432/appdb
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
      ports:
        - "18080:8080"
      restart: no
      depends_on:
        - bookmark-db

